import {describe,it,expect} from 'vitest';
import {env} from 'cloudflare:workers';
import {runDurableObjectAlarm,runInDurableObject} from 'cloudflare:test';
import type {ClientCommand,SessionUser} from '../../packages/contracts/index.js';
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const users=()=>Array.from({length:5},(_,i):SessionUser=>({accountId:`e2e-${i}-${crypto.randomUUID().slice(0,6)}`,username:`e2e_${i}`,displayName:`E2E ${i}`,avatar:'moon',locale:'ur-Roman'}));
async function connect(stub:any,u:SessionUser,playerId:string){const identity={sessionId:`s-${u.accountId}`,accountId:u.accountId,playerId,roomMemberId:playerId,protocolVersion:'cf-1.0.0',clientVersion:'1.0.0'};const r=await stub.fetch(new Request('http://internal/ws',{headers:{upgrade:'websocket','x-mafiyaar-internal':env.INTERNAL_ROUTING_SECRET,'x-mafiyaar-identity':JSON.stringify(identity)}}));const ws=r.webSocket!;ws.accept?.();return ws;}
let sequence=0;async function send(ws:WebSocket,value:any){const cmd={...value,sequence:++sequence,commandId:`e2e_${crypto.randomUUID().replaceAll('-','')}`} as ClientCommand;ws.send(JSON.stringify(cmd));await sleep(8);}
async function alarm(stub:any){await sleep(145);expect(await runDurableObjectAlarm(stub)).toBe(true);}

describe('local Cloudflare full match',()=>{
 it('completes a hosted-authority match through victory, archive, and rematch',async()=>{const us=users(),stub=env.MAFIYAAR_ROOMS.get(env.MAFIYAAR_ROOMS.newUniqueId());const first=await stub.initialize({publicCode:'E2EAB',codeLookupHmac:'e2e-hmac',creator:us[0]!,settings:{playerLimit:5,mafiaCount:1,preset:'test',startModel:'traditional'},expiresAt:Date.now()+3_600_000});const joined=[first,...await Promise.all(us.slice(1).map(u=>stub.join({user:u})))];const sockets=await Promise.all(us.map((u,i)=>connect(stub,u,joined[i]!.memberId)));for(let i=0;i<5;i++)await send(sockets[i]!,{type:'ready',roomId:'E2EAB',ready:true});await send(sockets[0]!,{type:'start',roomId:'E2EAB'});for(let i=0;i<5;i++)await send(sockets[i]!,{type:'ack_role',roomId:'E2EAB'});
   for(let guard=0;guard<40;guard++){const views=await Promise.all(us.map(u=>stub.getPlayerView(u.accountId))),phase=views[0]!.match?.phase;if(phase==='summary')break;if(phase==='night_action'){const mafiaIndex=views.findIndex(v=>v.match?.self.role==='mafia'&&v.match.self.alive);const civilian=views.find(v=>v.match?.self.role==='civilian'&&v.match.self.alive)!.match!.self.id;for(let i=0;i<5;i++){const v=views[i]!;if(!v.match!.self.canAct)continue;const target=i===mafiaIndex?civilian:v.match!.self.grid![0]!;await send(sockets[i]!,{type:'night_action',roomId:'E2EAB',phaseSequence:v.match!.phaseSequence,targetId:target,confirmed:true});}}
   if(phase==='vote'||phase==='runoff_vote'){const living=views.filter(v=>v.match?.self.alive),mafiaId=views.find(v=>v.match?.self.role==='mafia')!.match!.self.id;const target=living.map(v=>v.match!.self.id).find(id=>id!==mafiaId)!;for(let i=0;i<5;i++){const v=views[i]!;if(!v.match!.self.canAct)continue;let chosen=target;if(v.match!.self.id===target)chosen=living.map(x=>x.match!.self.id).find(id=>id!==target&&id!==mafiaId)??mafiaId;await send(sockets[i]!,{type:'vote',roomId:'E2EAB',phaseSequence:v.match!.phaseSequence,targetId:chosen,confirmed:true,runoff:phase==='runoff_vote'});}}
   await alarm(stub);}
   const end=await stub.getPlayerView(us[0]!.accountId);expect(end.match!.phase).toBe('summary');expect(end.match!.winner).toBe('mafia');await sleep(20);const archive=await runInDurableObject(stub,async(_instance:any,state)=>state.storage.sql.exec<any>('SELECT archive_status FROM room_snapshot WHERE id=1').one().archive_status);expect(archive).toMatch(/complete|pending/);await send(sockets[0]!,{type:'rematch',roomId:'E2EAB',sameSettings:true});const rematch=await stub.getPlayerView(us[0]!.accountId);expect(rematch.roomStatus).toBe('lobby');expect(rematch.match).toBeNull();for(const ws of sockets)ws.close(1000,'done');
 });
});
