import type { Locale, MatchSettings, PlayerView, SessionUser, Phase, VoteResult } from '../../../packages/contracts/index.js';
import { t, tf, roleInstruction } from '../../../packages/copy/index.js';
import { api, ApiError } from './api.js';
import { RealtimeClient, type ConnectionState } from './realtime.js';

type SessionPayload={user:SessionUser;csrfToken:string|null;activeRoom:{id:string;code:string;status:string}|null};
type Screen='home'|'create'|'join'|'profile'|'history'|'how'|'rules'|'privacy'|'settings'|'integrations'|'recover';
interface AppState{session:SessionPayload|null;authMode:'login'|'register'|'recover';screen:Screen;room:PlayerView|null;connection:ConnectionState;message:string;error:string;showRole:boolean;roleAckPending:boolean;overlay:null|'timeline'|'living'|'notes'|'votes';installPrompt:any;history:any[];profile:any;integrations:any;updateAvailable:boolean;publicConfig:any;challengeAction:null|'login'|'register'|'recovery'|'room_lookup';turnstileToken:string;}
const state:AppState={session:null,authMode:'login',screen:'home',room:null,connection:'offline',message:'',error:'',showRole:false,roleAckPending:false,overlay:null,installPrompt:null,history:[],profile:null,integrations:null,updateAvailable:false,publicConfig:null,challengeAction:null,turnstileToken:''};
const root=document.querySelector<HTMLElement>('#app')!;
let realtime:RealtimeClient|null=null;let countdown:any=null;let holdTimer:any=null;let wakeLock:any=null;
const esc=(v:unknown)=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]!));
const locale=():Locale=>state.session?.user.locale||'ur-Roman';
const nameFor=(id:string|null|undefined)=>state.room?.members.find(p=>p.id===id)?.displayName||'—';
const avatarFor=(id:string)=>state.room?.members.find(p=>p.id===id)?.avatar||'moon';
function setError(error:unknown){if(error instanceof ApiError&&error.code==='CHALLENGE_REQUIRED'){state.challengeAction=state.screen==='join'?'room_lookup':state.authMode==='register'?'register':state.authMode==='recover'?'recovery':'login';state.turnstileToken='';}state.error=error instanceof ApiError?error.message:error instanceof Error?error.message:'Kuch ghalat ho gaya.';render();}
const screenFromLocation=():Screen=>{const path=location.pathname;return /^\/join\/[A-HJ-NP-Z2-9]{5}$/i.test(path)?'join':(['create','join','profile','history','how','rules','privacy','settings','integrations','recover'].includes(path.slice(1))?path.slice(1):'home') as Screen;};
function navigate(screen:Screen){state.screen=screen;state.error='';history.pushState({screen},'',screen==='home'?'/':`/${screen}`);render();}
window.addEventListener('popstate',()=>{state.screen=screenFromLocation();render();});
window.addEventListener('beforeinstallprompt',(event:any)=>{event.preventDefault();state.installPrompt=event;render();});
window.addEventListener('online',()=>{state.connection='reconnecting';render();});window.addEventListener('offline',()=>{state.connection='offline';render();});
window.addEventListener('orientationchange',render);

async function boot(){
  state.publicConfig=await api<any>('/api/config').catch(()=>null);
  if('serviceWorker'in navigator){
    navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload());
    navigator.serviceWorker.register('/service-worker.js').then(reg=>{if(reg.waiting){state.updateAvailable=true;render()}reg.addEventListener('updatefound',()=>{const worker=reg.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller){state.updateAvailable=true;render()}})})}).catch(()=>{});
  }
  document.addEventListener('visibilitychange',async()=>{if(document.visibilityState==='visible'&&state.room){await enterRoom(state.room.roomId).catch(setError);await requestWakeLock()}else{await wakeLock?.release?.().catch(()=>{});wakeLock=null;}});
  const params=new URLSearchParams(location.search),pathJoin=location.pathname.match(/^\/join\/([A-HJ-NP-Z2-9]{5})$/i),joinCode=pathJoin?.[1]||params.get('code')||params.get('c'),joinToken=params.get('token')||params.get('t');if(joinCode){state.screen='join';sessionStorage.setItem('pendingRoomCode',joinCode.toUpperCase());if(joinToken)sessionStorage.setItem('pendingInviteToken',joinToken)}
  if(!('WebSocket'in window)||!('fetch'in window)){state.error='This browser is not supported. Use current iPhone Safari, Android Chrome, Edge, or Chrome.';render();return;}
  try{state.session=await api<SessionPayload>('/api/auth/session');const saved=localStorage.getItem('mafiyaar.activeRoomCode');if(saved){await enterRoom(saved).catch(()=>localStorage.removeItem('mafiyaar.activeRoomCode'));}await loadHome();}catch(error){if(error instanceof ApiError&&error.status===401)state.session=null;else state.error='Local server start karein, phir page reload karein.';}render();
}
async function requestWakeLock(){if(!state.room||document.visibilityState!=='visible'||!('wakeLock'in navigator))return;try{wakeLock=await (navigator as any).wakeLock.request('screen')}catch{wakeLock=null}}
async function loadHome(){if(!state.session)return;const [data,profile]=await Promise.all([api<any>('/api/home'),api<any>('/api/profile')]);state.history=data.history||[];state.profile={...profile.profile,statistics:profile.statistics};applyPreferences();}
function applyPreferences(){const p=state.profile;if(!p)return;document.documentElement.style.fontSize=`${16*Math.max(1,Math.min(2,Number(p.text_scale)||1))}px`;document.documentElement.classList.toggle('user-reduced-motion',Boolean(p.reduced_motion));}
async function enterRoom(id:string){localStorage.setItem('mafiyaar.activeRoomCode',id);state.room=(await api<{room:PlayerView}>(`/api/rooms/resolve/${encodeURIComponent(id)}`)).room;state.roleAckPending=false;realtime?.close();realtime=new RealtimeClient(view=>{const phaseChanged=state.room?.match?.phase!==view.match?.phase;state.room=view;if(phaseChanged){state.showRole=false;state.roleAckPending=false;}if(view.match?.self.acknowledged)state.roleAckPending=false;state.error='';render();},(connection,message)=>{state.connection=connection;if(message)state.error=message;render();},message=>{state.roleAckPending=false;state.error=message;render();});realtime.connect(id);await requestWakeLock();}
function send(command:any){if(!realtime){state.error='Realtime connection tayyar nahi.';render();return}realtime.command(command);}
async function copyText(value:string){try{await navigator.clipboard.writeText(value);return true}catch{const area=document.createElement('textarea');area.value=value;area.setAttribute('readonly','');area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();const ok=document.execCommand('copy');area.remove();return ok;}}

function shell(content:string){
  const l=locale();
  const connection=state.room?connectionBanner(l):'';
  const brand=state.room
    ? `<div class="brand" aria-label="MafiYaar active match"><span class="brand-mark">MY</span><span><b>MafiYaar</b><small>${esc(t(l,'brandLine'))}</small></span></div>`
    : `<button class="brand" data-nav="home" aria-label="MafiYaar home"><span class="brand-mark">MY</span><span><b>MafiYaar</b><small>${esc(t(l,'brandLine'))}</small></span></button>`;
  const profile=state.session
    ? state.room
      ? `<div class="avatar-button" aria-hidden="true">${esc(state.session.user.displayName.slice(0,1).toUpperCase())}</div>`
      : `<button class="avatar-button" data-nav="profile" aria-label="Profile">${esc(state.session.user.displayName.slice(0,1).toUpperCase())}</button>`
    : '';
  return `<div class="app-shell">${connection}<header class="topbar">${brand}${profile}</header><main>${state.updateAvailable?(state.room?`<div class="notice update" role="status">Naya version ready hai. Match ke baad update karein.</div>`:`<div class="notice update" role="status">Naya version ready hai.<button data-apply-update>Update</button></div>`):''}${state.error?`<div class="notice error" role="alert">${esc(state.error)}<button data-dismiss>×</button></div>`:''}${state.message?`<div class="notice success">${esc(state.message)}</div>`:''}${content}</main>${state.session&&!state.room?nav():''}${state.overlay?overlay():''}</div>`;
}
function connectionBanner(l:Locale){if(state.connection==='online')return'';const text=state.connection==='replaced'?t(l,'duplicateSession'):state.connection==='offline'?t(l,'offline'):t(l,'reconnecting');return`<div class="connection ${state.connection}" role="status">${esc(text)}</div>`;}
function nav(){return`<nav class="bottom-nav" aria-label="Primary"><button data-nav="home">Home</button><button data-nav="history">History</button><button data-nav="how">How to play</button><button data-nav="settings">Settings</button></nav>`;}

function render(){clearInterval(countdown);document.documentElement.lang=locale()==='en'?'en':'ur-Latn';document.documentElement.dataset.locale=locale();document.documentElement.classList.toggle('landscape',innerWidth>innerHeight&&innerWidth<900);
  if(!state.session)root.innerHTML=authScreen();else if(state.room)root.innerHTML=shell(roomScreen());else root.innerHTML=shell(regularScreen());bind();updateTimer();}
function authScreen(){const l:Locale='ur-Roman';const mode=state.authMode;return`<div class="auth-layout"><section class="auth-brand"><div class="wordmark">Mafi<span>Yaar</span></div><p>${esc(t(l,'brandLine'))}</p><small>${esc(t(l,'supportLine'))}</small></section><section class="auth-card">${state.updateAvailable?`<div class="notice update" role="status">Naya version ready hai.<button data-apply-update>Update</button></div>`:''}${state.error?`<div class="notice error">${esc(state.error)}</div>`:''}<div class="segmented"><button data-auth="login" class="${mode==='login'?'active':''}">Login</button><button data-auth="register" class="${mode==='register'?'active':''}">Create</button><button data-auth="recover" class="${mode==='recover'?'active':''}">Recover</button></div>${mode==='register'?registerForm():mode==='recover'?recoverForm():loginForm()}${challengeBox()}</section></div>`;}
function challengeBox(){return state.challengeAction?`<div class="challenge-wrap"><p>Security check complete karein.</p><div id="turnstile-widget"></div></div>`:'';}
function challengePayload(){return state.turnstileToken?{turnstileToken:state.turnstileToken}:{};}
function loginForm(){return`<form id="login-form"><h1>Wapas aa gaye?</h1><label>Username<input name="username" autocomplete="username" required minlength="3"></label><label>PIN<input name="pin" type="password" inputmode="numeric" autocomplete="current-password" required pattern="[0-9]{6}"></label><button class="primary" type="submit">Login</button><p class="form-help">Local demo: <code>mustafa / 864209</code> after running the seed command.</p></form>`;}
function registerForm(){return`<form id="register-form"><h1>Naya account banao</h1><label>Display name<input name="displayName" autocomplete="name" required minlength="2" maxlength="30"></label><label>Username<input name="username" autocomplete="username" required pattern="[a-zA-Z0-9_]{3,24}"></label><label>6 digit PIN<input name="pin" type="password" inputmode="numeric" autocomplete="new-password" required pattern="[0-9]{6}"></label><label>Recovery email <span>(optional)</span><input name="recoveryEmail" type="email" autocomplete="email"></label><button class="primary" type="submit">Account banao</button></form>`;}
function recoverForm(){return`<form id="recover-form"><h1>PIN bhool gaye?</h1><p>Recovery email configured ho to secure code bheja jayega. Local mode mein dev outbox use hota hai.</p><label>Username<input name="username" required></label><button class="primary" type="submit">Recovery shuru karo</button></form><hr style="border-color:var(--edge);margin:24px 0"><form id="complete-recovery-form"><h2>Recovery code mila?</h2><label>Recovery token<input name="token" required></label><label>Naya PIN<input name="pin" type="password" inputmode="numeric" required pattern="[0-9]{6}"></label><button class="primary" type="submit">PIN badlo</button></form>`;}

function regularScreen(){switch(state.screen){case'create':return createRoomScreen();case'join':return joinRoomScreen();case'profile':return profileScreen();case'history':return historyScreen();case'how':return infoScreen('Kaise khelna hai',howCopy());case'rules':return infoScreen('Rules',rulesCopy());case'privacy':return infoScreen('Privacy',privacyCopy());case'settings':return settingsScreen();case'integrations':return integrationsScreen();default:return homeScreen();}}
function homeScreen(){const l=locale();return`<section class="hero"><p class="eyebrow">TONIGHT</p><h1>${esc(t(l,'welcomeTitle'))}</h1><p>${esc(t(l,'welcomeBody'))}</p><div class="hero-actions"><button class="primary" data-nav="create">${esc(t(l,'createRoom'))}</button><button class="secondary" data-nav="join">${esc(t(l,'joinRoom'))}</button></div></section><section class="card-grid"><article class="card"><h2>Everyone plays</h2><p>Host app hai. Creator match shuru hote hi ordinary player ban jata hai.</p></article><article class="card"><h2>Phone secondary hai</h2><p>Night aur vote private. Discussion face-to-face.</p></article></section>${state.installPrompt?`<section class="install-card"><h2>${esc(t(l,'installTitle'))}</h2><p>${esc(t(l,'installBody'))}</p><button data-install>Install</button></section>`:`<section class="install-card subtle"><h2>App ki tarah use karein</h2><p>iPhone: Share → Add to Home Screen. Android: browser menu → Install app.</p></section>`}${state.history.length?`<section><div class="section-head"><h2>Recent matches</h2><button data-nav="history">Sab dekho</button></div>${historyRows(state.history.slice(0,3))}</section>`:''}`;}
function createRoomScreen(){return`<section class="page-head"><p class="eyebrow">NEW ROOM</p><h1>Game ka mood set karo</h1><p>Har option match ke rules snapshot mein save hota hai.</p></section><form id="create-room-form" class="settings-form"><label>Players limit<input name="playerLimit" type="number" min="5" max="20" value="8"></label><label>Mafia count<input name="mafiaCount" type="number" min="1" max="9" value="1"></label><fieldset><legend>Start</legend><label><input type="radio" name="startModel" value="opening" checked> 60s opening talk, phir night <b>Recommended</b></label><label><input type="radio" name="startModel" value="traditional"> Seedha night</label><label><input type="radio" name="startModel" value="day"> Pehle discussion aur vote</label></fieldset><label>Timing<select name="preset"><option value="standard">Standard</option><option value="fast">Fast</option><option value="relaxed">Relaxed</option></select></label><label>Alignment reveal<select name="alignmentReveal"><option value="on">Reveal after elimination</option><option value="off">Hide until summary</option></select></label><label>Raat ka Bachao<select name="nightProtection"><option value="bachao">On — MafiYaar</option><option value="off">Off — Classic</option></select></label><label>Multi-Mafia tie<select name="multiMafiaRule"><option value="random-tied">Random among tied submitted targets</option><option value="hidden-lead">Hidden rotating lead</option><option value="no-kill">No kill</option></select></label><output id="balance-output" class="balance-output">8 players, 1 Mafia — recommended.</output><button class="primary" type="submit">Room banao</button></form>`;}
function joinRoomScreen(){const pending=sessionStorage.getItem('pendingRoomCode')||'',token=sessionStorage.getItem('pendingInviteToken')||'';return`<section class="page-head"><p class="eyebrow">JOIN</p><h1>Code bolo, room mil jayega</h1></section><form id="join-room-form" class="join-form"><input type="hidden" name="token" value="${esc(token)}"><label>5-character room code<input name="code" maxlength="5" value="${esc(pending)}" autocomplete="off" autocapitalize="characters" required></label><button class="primary" type="submit">Room join karo</button>${challengeBox()}</form><p class="form-help">QR ko phone camera se scan karein; invite link code aur secure token dono fill karta hai.</p>`;}
function profileScreen(){const u=state.session!.user,s=state.profile?.statistics||{};return`<section class="page-head"><p class="eyebrow">PROFILE</p><h1>${esc(u.displayName)}</h1><p>@${esc(u.username)}</p></section><section class="stat-grid"><article><b>${Number(s.matches_played||0)}</b><small>Matches</small></article><article><b>${Number(s.wins||0)}</b><small>Wins</small></article><article><b>${Number(s.mafia_games||0)}</b><small>Mafia</small></article><article><b>${Number(s.civilian_games||0)}</b><small>Civilian</small></article></section><form id="profile-form" class="settings-form"><label>Display name<input name="displayName" value="${esc(u.displayName)}"></label><label>Avatar<select name="avatar">${['moon','match','mask','card','shadow'].map(a=>`<option value="${a}" ${u.avatar===a?'selected':''}>${a}</option>`).join('')}</select></label><label>Language<select name="locale"><option value="ur-Roman" ${u.locale==='ur-Roman'?'selected':''}>Roman Urdu</option><option value="en" ${u.locale==='en'?'selected':''}>English</option></select></label><button class="primary" type="submit">Save profile</button><button class="danger" type="button" data-logout>Log out</button></form>`;}
function settingsScreen(){const p=state.profile||{};return`<section class="page-head"><p class="eyebrow">ACCESSIBILITY</p><h1>Apne phone ke liye set karo</h1></section><form id="settings-form" class="settings-form"><label class="switch"><input name="reducedMotion" type="checkbox" ${state.profile?.reduced_motion?'checked':''}> Reduced motion</label><label class="switch"><input name="accessibleConfirmation" type="checkbox" ${state.profile?.accessible_confirmation?'checked':''}> Tap-to-confirm alternative</label><label>Text size<input name="textScale" type="range" min="1" max="2" step="0.1" value="${Number(p.text_scale||1)}"></label><button class="primary" type="submit">Save settings</button></form><section class="card"><h2>Device guidance</h2><p>Notifications silence karein, screen apne paas rakhein, aur private phases mein portrait use karein.</p><button data-load-integrations>Developer integration status</button></section>`;}
function integrationsScreen(){const data=state.integrations;return`<section class="page-head"><p class="eyebrow">DEVELOPER HEALTH</p><h1>Integration status</h1><p>Live secrets ya private game truth yahan expose nahi hoti.</p></section>${!data?`<div class="empty"><p>Status load karein.</p><button class="primary" data-load-integrations>Load status</button></div>`:`<section class="card"><h2>${esc(data.environment)} · ${esc(data.databaseProvider)}</h2>${Object.entries(data.health||{}).map(([name,value])=>`<div class="player-row"><span>${esc(name)}</span><b>${esc(typeof value==='object'?JSON.stringify(value):value)}</b></div>`).join('')}</section><section class="card"><h2>External activation</h2>${Object.entries(data.externalActivation||{}).map(([name,pending])=>`<div class="player-row"><span>${esc(name)}</span><b>${pending?'Pending credentials':'Active/local'}</b></div>`).join('')}</section>`}`;}
function historyScreen(){return`<section class="page-head"><p class="eyebrow">HISTORY</p><h1>Purane jhoot, purane vote</h1></section>${state.history.length?historyRows(state.history):`<div class="empty"><h2>Abhi koi match nahi</h2><p>Pehla room banao. Kahani yahin nazar ayegi.</p><button data-nav="create">Room banao</button></div>`}`;}
function historyRows(rows:any[]){return`<div class="history-list">${rows.map(r=>`<article><div><b>${esc(r.role||'Player')}</b><small>${r.completedAt?new Date(r.completedAt).toLocaleString():''}</small></div><strong class="${r.winner==='mafia'?'red':'brass'}">${esc(r.winner||'—')} win</strong></article>`).join('')}</div>`;}
function infoScreen(title:string,body:string){return`<section class="page-head"><h1>${esc(title)}</h1></section><article class="prose">${body}</article>`;}
function howCopy(){return`<h2>1. Har player apne phone se join karta hai</h2><p>Paper slips aur permanent Host ki zarurat nahi.</p><h2>2. Night par sab kuch choose karte hain</h2><p>Mafia victim choose karti hai. Raat ka Bachao on ho to living Civilians ka unique, strong prediction Mafia ka target bacha sakta hai. Morning par reason secret rehta hai.</p><h2>3. Discussion room mein hoti hai</h2><p>Phone timer aur public ready count dikhata hai. Sab living players ready hon to minimum discussion ke baad phase jaldi khatam ho sakta hai.</p><h2>4. Vote private, ledger public</h2><p>Deadline tak vote hidden. Resolution par candidate totals, voter names aur no-vote players ek saath khulte hain.</p>`;}
function rulesCopy(){return`<ul><li>Doosre player ki screen, reflection ya glasses mein mat dekho.</li><li>Eliminate hone ke baad bolna ya signal dena mana hai.</li><li>Self-vote disabled hai. Missed vote “no vote” hota hai.</li><li>Discussion mein sirf living players early-ready count mein aate hain; disconnect early transition ko rokta hai.</li><li>Raat ka Bachao sirf unique top living-Civilian prediction aur required threshold par kill block karta hai.</li><li>Pehli tie par runoff; doosri tie par koi eliminate nahi.</li><li>Mafia parity par foran jeet jati hai.</li></ul>`;}
function privacyCopy(){return`<p>MafiYaar minimum data rakhta hai: account identity, profile, sessions, room history aur completed-match statistics.</p><p>Raw PIN kabhi store nahi hota. Secret roles, live night actions aur unrevealed votes client ko broadcast nahi kiye jate.</p><p>Local build data aapke computer ki SQLite file mein rehta hai. Production provider wiring alag documentation mein hai.</p>`;}

function roomScreen(){const room=state.room!;if(!room.match)return lobbyScreen(room);switch(room.match.phase){case'role_reveal':return roleScreen(room);case'night_action':case'vote':case'runoff_vote':return actionScreen(room);case'morning':return morningScreen(room);case'discussion':case'opening_discussion':return discussionScreen(room);case'vote_resolution':return ledgerScreen(room);case'elimination':return eliminationScreen(room);case'victory':return victoryScreen(room);case'summary':return summaryScreen(room);case'technical_pause':return `<section class="public-moment"><p class="eyebrow">TECHNICAL PAUSE</p><h1>${esc(t(locale(),'technicalPause'))}</h1>${room.isCreator?`<button class="primary" data-resume-match>Resume</button><button class="danger" data-abandon-match>Match end karo</button>`:''}</section>`;case'abandoned':return publicMoment(t(locale(),'matchAbandoned'),t(locale(),'matchAbandoned'));default:return transitionScreen(room);}}
function lobbyScreen(room:PlayerView){
  const l=locale();
  const allReady=room.members.length>=5&&room.members.every(p=>p.ready&&p.connected);
  const settings=room.settings;
  const creatorSettings=room.isCreator?`<details class="room-settings-panel"><summary>Room settings badlo</summary><form id="room-settings-form" class="settings-form compact"><label>Players limit<input name="playerLimit" type="number" min="5" max="20" value="${settings.playerLimit}"></label><label>Mafia count<input name="mafiaCount" type="number" min="1" max="9" value="${settings.mafiaCount}"></label><label>Start<select name="startModel"><option value="opening" ${settings.startModel==='opening'?'selected':''}>Opening discussion</option><option value="traditional" ${settings.startModel==='traditional'?'selected':''}>Traditional night start</option><option value="day" ${settings.startModel==='day'?'selected':''}>Day start</option></select></label><label>Timing<select name="preset"><option value="standard" ${settings.preset==='standard'?'selected':''}>Standard</option><option value="fast" ${settings.preset==='fast'?'selected':''}>Fast</option><option value="relaxed" ${settings.preset==='relaxed'?'selected':''}>Relaxed</option></select></label><label>Alignment<select name="alignmentReveal"><option value="on" ${settings.alignmentReveal==='on'?'selected':''}>Reveal</option><option value="off" ${settings.alignmentReveal==='off'?'selected':''}>Hide until summary</option></select></label><label>Raat ka Bachao<select name="nightProtection"><option value="bachao" ${settings.nightProtection==='bachao'?'selected':''}>On — MafiYaar</option><option value="off" ${settings.nightProtection==='off'?'selected':''}>Off — Classic</option></select></label><label>Multi-Mafia tie<select name="multiMafiaRule"><option value="random-tied" ${settings.multiMafiaRule==='random-tied'?'selected':''}>Random tied target</option><option value="hidden-lead" ${settings.multiMafiaRule==='hidden-lead'?'selected':''}>Hidden lead</option><option value="no-kill" ${settings.multiMafiaRule==='no-kill'?'selected':''}>No kill</option></select></label><button class="secondary" type="submit">Settings save karo</button><small>Settings badalne par sab players dobara ready karenge.</small></form></details>`:'';
  return `<section class="room-code"><p class="eyebrow">ROOM CODE</p><h1>${esc(room.roomCode)}</h1><p>Code bolo ya QR scan karwao.</p><img src="/api/rooms/${esc(room.roomId)}/qr" alt="Scannable room code ${esc(room.roomCode)}"><button data-copy-room>Invite copy karo</button></section><section class="roster"><div class="section-head"><h2>${room.members.length} in the room</h2><span>${esc(settings.startModel)} · ${esc(settings.preset)}</span></div>${room.members.map(p=>playerRow(p)).join('')}</section>${creatorSettings}<section class="readiness"><h2>Phone check</h2><ul><li>Notifications silence</li><li>Screen private</li><li>Portrait orientation</li><li>Doosri screen mat dekho</li></ul>${room.isCreator?`<button class="secondary" data-ready>${room.members.find(p=>p.displayName===state.session?.user.displayName)?.ready?t(l,'notReady'):t(l,'ready')}</button><button class="primary" data-start ${allReady?'':'disabled'}>${esc(t(l,'startMatch'))}</button><small>${allReady?'Sab ready.':'Kam az kam 5 connected aur ready players chahiye.'}</small>`:`<button class="primary" data-ready>${room.members.find(p=>p.displayName===state.session?.user.displayName)?.ready?t(l,'notReady'):t(l,'ready')}</button>`}<button class="secondary leave-room" data-leave-room>Room chhoro</button></section>`;
}
function playerRow(p:any){return`<div class="player-row"><span class="avatar">${esc(p.displayName.slice(0,1))}</span><div><b>${esc(p.displayName)}</b><small>${p.connected?'Connected':'Reconnecting'}</small></div><strong>${p.ready?'Ready':'Not ready'}</strong></div>`;}
function roleScreen(room:PlayerView){
  const l=locale(),self=room.match!.self;
  const role=self.role;
  const acknowledged=self.acknowledged||state.roleAckPending;
  return`<section class="private-screen role-screen"><p class="eyebrow">${esc(t(l,'yourRole'))}</p>${!state.showRole?`<div class="role-lock"><div class="lock-symbol">?</div><h1>${esc(t(l,'roleHidden'))}</h1><button class="hold-button" data-reveal-role>${esc(t(l,'revealRole'))}<span></span></button></div>`:`<div class="role-revealed ${role==='mafia'?'mafia-role':'civilian-role'}"><p class="eyebrow">${esc(t(l,'youAre'))}</p><h1>${esc(t(l,role==='mafia'?'mafia':'civilian'))}</h1><p>${esc(t(l,role==='mafia'?'mafiaBody':'civilianBody'))}</p>${self.teammates?.length?`<div class="teammates"><small>${esc(t(l,'withYou'))}</small>${self.teammates.map(id=>`<b>${esc(nameFor(id))}</b>`).join('')}</div>`:''}${acknowledged?`<div class="notice success" role="status" aria-live="polite"><b>Samajh aa gaya.</b><span>Baqi players ka wait ho raha hai.</span></div>`:`<button class="primary" data-ack-role>${esc(t(l,'acknowledge'))}</button>`}</div>`}</section>`;
}
function transitionScreen(room:PlayerView){const m=room.match!,l=locale();const labels:any={night_transition:[t(l,'night'),t(l,'nightKeepPrivate')],night_resolution:[t(l,'nightResolutionTitle'),t(l,'neutralResolutionBody')],vote_transition:[t(l,'vote'),t(l,'voteTransitionBody')],runoff_discussion:[t(l,'runoff'),m.tieCandidates.map(nameFor).join(' / ')],vote_resolution:[t(l,'ledger'),t(l,'voteResolutionBody')]};const [title,body]=labels[m.phase]||[t(l,'pleaseWait'),t(l,'synchronizing')];return publicMoment(title,body,true);}
function publicMoment(title:string,body:string,timer=false){return`<section class="public-moment"><p class="eyebrow">MAFIYAAR</p><h1>${esc(title)}</h1><p>${esc(body)}</p>${timer?timerMarkup():''}</section>`;}
function timerMarkup(){return`<div class="timer" data-timer>--:--</div>`;}
function actionScreen(room:PlayerView){const m=room.match!,self=m.self,l=locale(),isNight=m.phase==='night_action',isRunoff=m.phase==='runoff_vote';const instruction=isNight?roleInstruction(l,self.role,self.alive):!self.alive?t(l,'spectatorVoteInstruction'):t(l,'voteInstruction');const selected=self.selectedTargetId;return`<section class="private-screen action-screen ${isNight?`night-${self.role||'spectator'}`:'vote-action'}"><div class="action-head"><div><p class="eyebrow">${isNight?t(l,'night'):isRunoff?t(l,'runoff'):t(l,'vote')} · ${esc(t(l,'round'))} ${m.round}</p><p class="instruction">${esc(instruction)}</p></div>${timerMarkup()}</div><div class="target-grid" data-grid>${(self.grid||[]).map(id=>`<button class="target-card ${selected===id?'selected':''}" data-target="${esc(id)}" aria-pressed="${selected===id}"><span class="avatar">${esc(nameFor(id).slice(0,1))}</span><b>${esc(nameFor(id))}</b><small>${esc(avatarFor(id))}</small></button>`).join('')}</div><div class="confirm-zone">${selected?`<button class="hold-button ${self.submissionConfirmed?'confirmed':''}" data-confirm>${self.submissionConfirmed?esc(t(l,'confirmed')):esc(room.settings.confirmationMode==='accessible-tap'?t(l,'tapConfirm'):t(l,'holdConfirm'))}<span></span></button>`:`<p>${esc(t(l,'chooseFirst'))}</p>`}</div>${!self.alive?`<div class="spectator-note"><b>${esc(t(l,'spectatorTitle'))}</b><p>${esc(t(l,'spectatorBody'))}</p><button data-overlay="notes">${esc(t(l,'privateNotes'))}</button></div>`:''}</section>`;}
function morningScreen(room:PlayerView){const m=room.match!,l=locale();const victim=m.lastVictimId;return`<section class="public-moment morning"><p class="eyebrow">${esc(t(l,'morning'))} · ${esc(t(l,'round'))} ${m.round}</p><h1>${victim?esc(tf(l,'morningVictim',{name:nameFor(victim)})):esc(t(l,'noKill'))}</h1>${victim?`<p>${room.members.find(p=>p.id===victim)?.revealedRole?esc(tf(l,'revealedRole',{name:nameFor(victim),role:room.members.find(p=>p.id===victim)!.revealedRole!})):esc(t(l,'hiddenRoleResult'))}</p>`:''}${timerMarkup()}</section>`;}
function discussionScreen(room:PlayerView){const m=room.match!,l=locale(),ready=m.discussionReady;const nextIsVote=m.phase!=='opening_discussion'||room.settings.startModel==='day';const label=nextIsVote?'Vote ke liye ready':'Agla phase ke liye ready';const status=ready?ready.advanceAt?ready.advanceAt-(realtime?.serverNow()||Date.now())<=3000?'Sab ready. Vote 3 second mein shuru hoga.':'Sab ready. Minimum discussion complete hote hi agla phase shuru hoga.':`${ready.readyCount}/${ready.total} ready`:'';return`<section class="discussion-screen"><p class="eyebrow">ROUND ${m.round} · ${room.members.filter(p=>p.alive).length} ALIVE</p>${timerMarkup()}<h1>${esc(t(l,'headsUp'))}</h1>${ready&&m.self.alive?`<div class="discussion-ready-panel"><strong>${esc(status)}</strong><button class="${ready.selfReady?'secondary':'primary'}" data-discussion-ready ${ready.locked?'disabled':''}>${ready.selfReady?'Ready cancel karo':esc(label)}</button></div>`:''}<div class="quiet-actions"><button data-overlay="living">${esc(t(l,'whoIsAlive'))}</button><button data-overlay="timeline">${esc(t(l,'whatHappened'))}</button>${m.self.alive?'':`<button data-overlay="notes">${esc(t(l,'privateNotes'))}</button>`}${room.isCreator?`<button data-pause-match>Technical pause</button><button class="danger" data-abandon-match>Match end karo</button>`:''}</div></section>`;}

function voteRows(result:VoteResult){return result.candidates.map(candidateId=>{const voters=result.ledger.filter(row=>row.targetId===candidateId).map(row=>nameFor(row.voterId));return{candidateId,voters,count:voters.length};}).sort((a,b)=>b.count-a.count||nameFor(a.candidateId).localeCompare(nameFor(b.candidateId)));}
function voteResultTable(result:VoteResult){const noVotes=result.noVotePlayerIds.map(nameFor);return`<div class="vote-table">${voteRows(result).map(row=>`<div class="vote-row ${result.eliminatedId===row.candidateId?'eliminated':''}"><div><b>${esc(nameFor(row.candidateId))}</b><small>${row.voters.length?esc(row.voters.join(' · ')):'—'}</small></div><strong>${row.count}</strong></div>`).join('')}${noVotes.length?`<div class="vote-row no-vote"><div><b>No vote</b><small>${esc(noVotes.join(' · '))}</small></div><strong>${noVotes.length}</strong></div>`:''}</div>`;}
function voteHistoryMarkup(history:VoteResult[]){return history.length?history.map(result=>`<section class="vote-history-round"><p class="eyebrow">ROUND ${result.round} · ${result.runoff?'RUNOFF':'MAIN VOTE'}</p><h3>${result.eliminatedId?`${esc(nameFor(result.eliminatedId))} eliminate ho gaya`:result.tiedIds.length>1?'Vote barabar ho gaya':'Koi eliminate nahi hua'}</h3>${voteResultTable(result)}</section>`).join(''):`<p>Abhi voting history nahi hai.</p>`;}

function ledgerScreen(room:PlayerView){const m=room.match!,l=locale(),result=m.lastVoteResult;if(!result)return`<section class="ledger-screen"><p class="eyebrow">${esc(t(l,'ledger'))}</p><p>Vote resolve ho rahe hain.</p>${timerMarkup()}</section>`;const eliminated=result.eliminatedId?room.members.find(player=>player.id===result.eliminatedId):null;const eliminatedVotes=result.eliminatedId?result.ledger.filter(row=>row.targetId===result.eliminatedId).length:0;const title=eliminated?`${esc(eliminated.displayName)} eliminate ho gaya`:result.tiedIds.length>1?'Vote barabar ho gaya':'Koi eliminate nahi hua';const role=eliminated?.revealedRole?`${esc(eliminated.displayName)} ${esc(eliminated.revealedRole)} tha`:eliminated?'Role match ke end par reveal hoga':'';return`<section class="ledger-screen"><p class="eyebrow">${esc(t(l,'ledger'))} · ${result.runoff?'RUNOFF':'MAIN VOTE'}</p><h1>${title}</h1>${eliminated?`<p><b>${eliminatedVotes} votes mile</b></p><p>${role}</p>`:''}${voteResultTable(result)}${timerMarkup()}</section>`;}

function eliminationScreen(room:PlayerView){const m=room.match!,l=locale();if(!m.lastEliminatedId)return`<section class="public-moment"><p class="eyebrow">${esc(t(l,'noEliminationLabel'))}</p><h1>${esc(t(l,'noElimination'))}</h1>${timerMarkup()}</section>`;const p=room.members.find(p=>p.id===m.lastEliminatedId);return`<section class="public-moment elimination"><p class="eyebrow">${esc(t(l,'votedOutLabel'))}</p><h1>${esc(tf(l,'votedOut',{name:nameFor(m.lastEliminatedId)}))}</h1><p>${p?.revealedRole?esc(tf(l,'revealedRole',{name:nameFor(p.id),role:p.revealedRole})):esc(t(l,'hiddenAlignmentSummary'))}</p>${timerMarkup()}</section>`;}
function victoryScreen(room:PlayerView){const m=room.match!,l=locale(),mafia=m.winner==='mafia';return`<section class="victory ${mafia?'mafia-win':'civilian-win'}"><p class="eyebrow">${esc(t(l,'matchComplete'))}</p><h1>${esc(t(l,mafia?'mafiaWin':'civilianWin'))}</h1><p>${esc(t(l,mafia?'mafiaWinBody':'civilianWinBody'))}</p>${timerMarkup()}</section>`;}
function summaryScreen(room:PlayerView){const m=room.match!,l=locale(),summary=m.summary;const protections=(summary?.nightResults||[]).filter(result=>result.outcome==='protected');return`<section class="page-head"><p class="eyebrow">${esc(t(l,'summary'))}</p><h1>${esc(tf(l,'summaryTitle',{round:m.round}))}</h1></section><div class="summary-grid">${summary?.players.map(p=>`<article><span class="avatar">${esc(p.displayName.slice(0,1))}</span><div><b>${esc(p.displayName)}</b><small>${esc(p.role)} · ${p.eliminated?`${p.eliminated.reason}, round ${p.eliminated.round}`:'survived'}</small></div></article>`).join('')||''}</div>${protections.length?`<section class="protection-summary"><h2>Raat ka Bachao</h2>${protections.map(result=>`<article><b>Round ${result.round}: Civilians ne ${esc(nameFor(result.targetId))} ko Mafia ke nishane se bacha liya.</b><small>${result.protectionVotes} sahi votes · ${result.protectionRequired} required</small></article>`).join('')}</section>`:''}<section class="prediction-summary"><h2>${esc(t(l,'predictionTitle'))}</h2>${summary?.predictions.filter(p=>p.total>0).map(p=>`<div class="player-row"><span>${esc(nameFor(p.actorId))}</span><b>${p.correct} / ${p.total}</b></div>`).join('')||`<p>${esc(t(l,'noPredictions'))}</p>`}</section><div class="hero-actions"><button class="primary" data-rematch>${esc(t(l,'dealAgain'))}</button><button class="secondary" data-rematch-settings>Settings badlo</button><button data-overlay="votes">${esc(t(l,'votingHistory'))}</button></div>`;}

function noteKey(){return`mafiyaar-notes:${state.room?.match?.id||'none'}:${state.room?.match?.self.id||'none'}`;}
function overlay(){const room=state.room!,m=room.match!,l=locale();const body=state.overlay==='notes'?`<h2>${esc(t(l,'privateNotes'))}</h2><p>${esc(t(l,'privateNotesBody'))}</p><textarea id="private-notes" rows="8" maxlength="2000">${esc(localStorage.getItem(noteKey())||'')}</textarea><button class="primary" data-save-notes>${esc(t(l,'saveNotes'))}</button>`:state.overlay==='living'?`<h2>${esc(t(l,'whoIsAlive'))}</h2>${room.members.map(p=>`<div class="player-row ${p.alive?'':'dead'}"><span>${esc(p.displayName)}</span><b>${p.alive?esc(t(l,'alive')):esc(p.eliminated?.reason||t(l,'out'))}</b></div>`).join('')}`:`<h2>${esc(t(l,'publicTimeline'))}</h2>${m.publicEvents.slice().reverse().map(e=>`<article class="timeline-row"><b>${esc(e.type.replaceAll('_',' '))}</b><small>${esc(t(l,'round'))} ${e.round}</small></article>`).join('')}`;return`<div class="overlay" role="dialog" aria-modal="true"><div class="sheet"><button class="sheet-close" data-overlay-close aria-label="Close">×</button>${body}</div></div>`;}


function renderTurnstile(){const target=document.querySelector<HTMLElement>('#turnstile-widget'),api=(window as any).turnstile,siteKey=state.publicConfig?.turnstile?.siteKey;if(!target||!api||!siteKey)return;api.render(target,{sitekey:siteKey,action:state.challengeAction,theme:'dark',size:'flexible',callback:(token:string)=>{state.turnstileToken=token;state.error='';}});}
function updateBalanceHint(){const form=document.querySelector<HTMLFormElement>('#create-room-form'),out=document.querySelector<HTMLOutputElement>('#balance-output');if(!form||!out)return;const players=Number(new FormData(form).get('playerLimit')||8),mafia=Number(new FormData(form).get('mafiaCount')||1),recommended=players<=8?1:players<=13?2:3;if(mafia>=players-mafia){out.textContent='Invalid — match Mafia parity se shuru nahi ho sakta.';out.className='balance-output danger';}else if(mafia===recommended){out.textContent=`${players} players, ${mafia} Mafia — recommended starting point.`;out.className='balance-output good';}else if(mafia>recommended){out.textContent=`${players} players, ${mafia} Mafia — Mafia advantage; experimental.`;out.className='balance-output warn';}else{out.textContent=`${players} players, ${mafia} Mafia — Civilian advantage; longer match possible.`;out.className='balance-output warn';}}
function updateTimer(){const el=document.querySelector<HTMLElement>('[data-timer]');const end=state.room?.match?.phaseEndsAt;if(!el||!end)return;const tick=()=>{const now=realtime?.serverNow()||Date.now();const remaining=Math.max(0,end-now);const seconds=Math.ceil(remaining/1000);el.textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;el.classList.toggle('urgent',remaining<=10_000);};tick();countdown=setInterval(tick,200);}
function bind(){
  document.querySelectorAll<HTMLElement>('[data-nav]').forEach(el=>el.onclick=()=>{state.room=null;realtime?.close();navigate(el.dataset.nav as Screen)});
  document.querySelectorAll<HTMLElement>('[data-auth]').forEach(el=>el.onclick=()=>{state.authMode=el.dataset.auth as any;state.error='';state.challengeAction=null;state.turnstileToken='';render()});
  document.querySelector<HTMLElement>('[data-dismiss]')?.addEventListener('click',()=>{state.error='';render()});
  document.querySelectorAll<HTMLInputElement>('#create-room-form input[name=playerLimit],#create-room-form input[name=mafiaCount]').forEach(el=>el.addEventListener('input',updateBalanceHint));updateBalanceHint();renderTurnstile();
  document.querySelector<HTMLFormElement>('#login-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);try{state.session=await api<SessionPayload>('/api/auth/login',{method:'POST',body:JSON.stringify({...Object.fromEntries(f),...challengePayload()})});await loadHome();render()}catch(x){setError(x)}});
  document.querySelector<HTMLFormElement>('#register-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);try{state.session=await api<SessionPayload>('/api/auth/register',{method:'POST',body:JSON.stringify({...Object.fromEntries(f),locale:'ur-Roman',...challengePayload()})});await loadHome();render()}catch(x){setError(x)}});
  document.querySelector<HTMLFormElement>('#recover-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);try{const r=await api<any>('/api/auth/recovery/request',{method:'POST',body:JSON.stringify({...Object.fromEntries(f),...challengePayload()})});state.message=r.developmentToken?`Local recovery token: ${r.developmentToken}`:'Recovery available ho to message bhej diya gaya.';render()}catch(x){setError(x)}});
  document.querySelector<HTMLFormElement>('#complete-recovery-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);try{await api('/api/auth/recovery/complete',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});state.message='PIN update ho gaya. Ab login karein.';state.authMode='login';render()}catch(x){setError(x)}});
  document.querySelector<HTMLFormElement>('#create-room-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);const body:any=Object.fromEntries(f);body.playerLimit=Number(body.playerLimit);body.mafiaCount=Number(body.mafiaCount);try{const r=await api<any>('/api/rooms/create',{method:'POST',body:JSON.stringify(body)});await enterRoom(r.room.roomId)}catch(x){setError(x)}});
  document.querySelector<HTMLFormElement>('#room-settings-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);const settings:any=Object.fromEntries(f);settings.playerLimit=Number(settings.playerLimit);settings.mafiaCount=Number(settings.mafiaCount);send({type:'update_settings',roomId:state.room!.roomId,settings});});
  document.querySelector<HTMLFormElement>('#join-room-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);try{const r=await api<any>(`/api/rooms/resolve/${encodeURIComponent(String(f.get('code')||''))}`,{method:'POST',body:JSON.stringify({token:f.get('token'),...challengePayload()})});sessionStorage.removeItem('pendingRoomCode');sessionStorage.removeItem('pendingInviteToken');await enterRoom(r.room.roomId)}catch(x){setError(x)}});
  document.querySelector<HTMLFormElement>('#profile-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);try{const r=await api<any>('/api/profile',{method:'PUT',body:JSON.stringify(Object.fromEntries(f))});state.session!.user={...state.session!.user,displayName:r.profile.display_name,avatar:r.profile.avatar,locale:r.profile.locale};state.profile={...r.profile,statistics:r.statistics};state.message='Profile save ho gaya.';render()}catch(x){setError(x)}});
  document.querySelector<HTMLFormElement>('#settings-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);try{const r=await api<any>('/api/profile',{method:'PUT',body:JSON.stringify({reducedMotion:f.has('reducedMotion'),accessibleConfirmation:f.has('accessibleConfirmation'),textScale:Number(f.get('textScale'))})});state.profile={...r.profile,statistics:r.statistics||state.profile?.statistics};applyPreferences();state.message='Settings save ho gayi.';render()}catch(x){setError(x)}});
  document.querySelector<HTMLElement>('[data-logout]')?.addEventListener('click',async()=>{await api('/api/auth/logout',{method:'POST'}).catch(()=>{});state.session=null;state.room=null;localStorage.removeItem('mafiyaar.activeRoomCode');realtime?.close();render()});
  document.querySelector<HTMLElement>('[data-apply-update]')?.addEventListener('click',async()=>{const reg=await navigator.serviceWorker.getRegistration();reg?.waiting?.postMessage('SKIP_WAITING')});
  document.querySelectorAll<HTMLElement>('[data-load-integrations]').forEach(el=>el.onclick=async()=>{try{state.integrations=await api<any>('/api/integrations');navigate('integrations')}catch(x){setError(x)}});
  document.querySelector<HTMLElement>('[data-install]')?.addEventListener('click',async()=>{await state.installPrompt?.prompt();state.installPrompt=null;render()});
  document.querySelector<HTMLElement>('[data-copy-room]')?.addEventListener('click',async()=>{try{const invite=await api<any>(`/api/rooms/${encodeURIComponent(state.room!.roomId)}/invite`,{method:'POST'});const copied=await copyText(invite.inviteUrl);state.message=copied?'Invite copy ho gaya.':`Invite: ${invite.inviteUrl}`;render()}catch(x){setError(x)}});
  document.querySelector<HTMLElement>('[data-ready]')?.addEventListener('click',()=>{const me=state.room!.members.find(p=>p.displayName===state.session!.user.displayName);send({type:'ready',roomId:state.room!.roomId,ready:!me?.ready})});
  document.querySelector<HTMLElement>('[data-start]')?.addEventListener('click',()=>send({type:'start',roomId:state.room!.roomId}));
  const reveal=document.querySelector<HTMLElement>('[data-reveal-role]');if(reveal)hold(reveal,()=>{state.showRole=true;render()},900);
  document.querySelector<HTMLElement>('[data-ack-role]')?.addEventListener('click',()=>{
    if(state.roleAckPending||state.room?.match?.self.acknowledged)return;
    if(state.connection!=='online'){
      state.error='Connection wapas aane dein, phir Samajh gaya dabayein.';
      render();
      return;
    }
    state.roleAckPending=true;
    state.error='';
    const roomId=state.room!.roomId;
    render();
    send({type:'ack_role',roomId});
  });
  document.querySelectorAll<HTMLElement>('[data-target]').forEach(el=>el.onclick=()=>{const m=state.room!.match!,type=m.phase==='night_action'?'night_action':'vote';send(type==='night_action'?{type,roomId:state.room!.roomId,targetId:el.dataset.target,confirmed:false}:{type,roomId:state.room!.roomId,targetId:el.dataset.target,confirmed:false,runoff:m.phase==='runoff_vote'})});
  const confirm=document.querySelector<HTMLElement>('[data-confirm]');if(confirm){const act=()=>{const m=state.room!.match!,targetId=m.self.selectedTargetId;if(m.phase==='night_action')send({type:'night_action',roomId:state.room!.roomId,targetId,confirmed:true});else send({type:'vote',roomId:state.room!.roomId,targetId,confirmed:true,runoff:m.phase==='runoff_vote'});};if(state.room!.settings.confirmationMode==='accessible-tap')confirm.onclick=act;else hold(confirm,act,1200);}
  document.querySelector<HTMLElement>('[data-rematch]')?.addEventListener('click',()=>send({type:'rematch',roomId:state.room!.roomId,sameSettings:true}));
  document.querySelector<HTMLElement>('[data-rematch-settings]')?.addEventListener('click',()=>send({type:'rematch',roomId:state.room!.roomId,sameSettings:false}));

  document.querySelector<HTMLElement>('[data-pause-match]')?.addEventListener('click',()=>send({type:'pause',roomId:state.room!.roomId,reason:'Creator technical pause'}));
  document.querySelector<HTMLElement>('[data-resume-match]')?.addEventListener('click',()=>send({type:'resume',roomId:state.room!.roomId}));
  document.querySelector<HTMLElement>('[data-abandon-match]')?.addEventListener('click',()=>{if(window.confirm('Match end karna hai?'))send({type:'abandon',roomId:state.room!.roomId,reason:'Creator ended match'})});
  document.querySelector<HTMLElement>('[data-leave-room]')?.addEventListener('click',async()=>{try{await api(`/api/rooms/${encodeURIComponent(state.room!.roomId)}/leave`,{method:'POST'});realtime?.close();state.room=null;localStorage.removeItem('mafiyaar.activeRoomCode');await loadHome();navigate('home')}catch(x){setError(x)}});
  document.querySelector<HTMLElement>('[data-save-notes]')?.addEventListener('click',()=>{const value=(document.querySelector<HTMLTextAreaElement>('#private-notes')?.value||'').slice(0,2000);localStorage.setItem(noteKey(),value);state.message='Private notes save ho gayi.';state.overlay=null;render()});
  document.querySelectorAll<HTMLElement>('[data-overlay]').forEach(el=>el.onclick=()=>{state.overlay=el.dataset.overlay as any;render()});document.querySelector<HTMLElement>('[data-overlay-close]')?.addEventListener('click',()=>{state.overlay=null;render()});
}
function hold(el:HTMLElement,action:()=>void,ms:number){let started=0;const start=()=>{started=Date.now();el.classList.add('holding');holdTimer=setTimeout(()=>{el.classList.remove('holding');action()},ms)};const cancel=()=>{if(Date.now()-started<ms){clearTimeout(holdTimer);el.classList.remove('holding')}};el.addEventListener('pointerdown',start);el.addEventListener('pointerup',cancel);el.addEventListener('pointerleave',cancel);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();start()}});el.addEventListener('keyup',cancel);}
boot();
