import {describe,it,expect} from 'vitest';
import {env} from 'cloudflare:workers';
import {authed,register,request} from '../helpers/http.js';

describe('full-stack Worker HTTP boundary',()=>{
  it('serves health, version and Static Assets through one Worker',async()=>{expect((await request('/health')).status).toBe(200);expect((await request('/version')).status).toBe(200);const page=await request('/');expect(page.status).toBe(200);expect(page.headers.get('content-type')).toContain('text/html');expect(await page.text()).toContain('MafiYaar');});
  it('creates a random Durable Object room without exposing its ID',async()=>{const s=await register(crypto.randomUUID().slice(0,8));const r=await authed('/api/rooms/create',s,{method:'POST',body:JSON.stringify({playerLimit:6,mafiaCount:1,preset:'test'})});expect(r.status).toBe(201);const text=await r.text();const body=JSON.parse(text);expect(body.room.roomCode).toMatch(/^[A-HJ-NP-Z2-9]{5}$/);const record=await env.DB.prepare('SELECT durable_object_id,code_lookup_hmac FROM room_codes').first<any>();expect(record.durable_object_id).toBeTruthy();expect(text).not.toContain(record.durable_object_id);expect(text).not.toContain(record.code_lookup_hmac);});
  it('issues an opaque short-lived connection ticket and stores only a digest',async()=>{const s=await register(crypto.randomUUID().slice(0,8));const created=await authed('/api/rooms/create',s,{method:'POST',body:JSON.stringify({playerLimit:6,mafiaCount:1,preset:'test'})});const code=(await created.json() as any).room.roomCode;const res=await authed(`/api/rooms/${code}/connection-ticket`,s,{method:'POST',body:JSON.stringify({clientVersion:'1.0.0',protocolVersion:'cf-1.0.0'})});expect(res.status).toBe(200);const body=await res.json() as any;expect(body.ticket).toMatch(/^[A-Za-z0-9_-]{32,}$/);const row=await env.DB.prepare('SELECT ticket_digest FROM connection_tickets').first<any>();expect(row.ticket_digest).not.toBe(body.ticket);});
  it('rejects cross-origin WebSocket attempts before consuming the ticket',async()=>{const s=await register(crypto.randomUUID().slice(0,8));const created=await authed('/api/rooms/create',s,{method:'POST',body:JSON.stringify({playerLimit:6,mafiaCount:1,preset:'test'})});const code=(await created.json() as any).room.roomCode;const t=await authed(`/api/rooms/${code}/connection-ticket`,s,{method:'POST',body:JSON.stringify({clientVersion:'1.0.0',protocolVersion:'cf-1.0.0'})});const ticket=(await t.json() as any).ticket;const cross=await request(`/ws/connect/${ticket}`,{headers:{upgrade:'websocket',origin:'https://evil.example',cookie:s.cookie}});expect(cross.status).toBe(404);const row=await env.DB.prepare('SELECT used_at FROM connection_tickets').first<any>();expect(row.used_at).toBeNull();});
});
