import {describe,it,expect} from 'vitest';
import {env} from 'cloudflare:workers';
import {runInDurableObject} from 'cloudflare:test';
import type {SessionUser} from '../../packages/contracts/index.js';
const user=(room:number,i:number):SessionUser=>({accountId:`load-${room}-${i}-${crypto.randomUUID().slice(0,5)}`,username:`load_${room}_${i}`,displayName:`L${room}-${i}`,avatar:'moon',locale:'ur-Roman'});
async function connect(stub:any,u:SessionUser,playerId:string){const identity={sessionId:`s-${u.accountId}`,accountId:u.accountId,playerId,roomMemberId:playerId,protocolVersion:'cf-1.0.0',clientVersion:'1.0.0'};const r=await stub.fetch(new Request('http://internal/ws',{headers:{upgrade:'websocket','x-mafiyaar-internal':env.INTERNAL_ROUTING_SECRET,'x-mafiyaar-identity':JSON.stringify(identity)}}));const ws=r.webSocket!;ws.accept?.();return ws;}
describe('local realtime capacity model',()=>{
 it('accepts twenty experimental clients in one room with small attachments',async()=>{const stub=env.MAFIYAAR_ROOMS.get(env.MAFIYAAR_ROOMS.newUniqueId()),users=Array.from({length:20},(_,i)=>user(1,i)),first=await stub.initialize({publicCode:'LDAAA',codeLookupHmac:'load-hmac',creator:users[0]!,settings:{playerLimit:20,mafiaCount:3,preset:'test'},expiresAt:Date.now()+100000}),members=[first,...await Promise.all(users.slice(1).map(u=>stub.join({user:u})))],sockets=await Promise.all(users.map((u,i)=>connect(stub,u,members[i]!.memberId)));const data=await runInDurableObject(stub,async(_i:any,state)=>state.getWebSockets().map((ws:WebSocket)=>JSON.stringify(ws.deserializeAttachment()).length));expect(data).toHaveLength(20);expect(Math.max(...data)).toBeLessThan(1024);for(const ws of sockets)ws.close(1000,'done');});
 it('keeps five simultaneous rooms isolated',async()=>{const rooms=await Promise.all(Array.from({length:5},async(_,r)=>{const stub=env.MAFIYAAR_ROOMS.get(env.MAFIYAAR_ROOMS.newUniqueId()),u=user(r,0),code=`LD${String.fromCharCode(65+r)}BC`;await stub.initialize({publicCode:code,codeLookupHmac:`h-${r}`,creator:u,settings:{playerLimit:6,preset:'test'},expiresAt:Date.now()+100000});return{stub,u,code};}));for(const x of rooms)expect((await x.stub.getPlayerView(x.u.accountId)).roomCode).toBe(x.code);});
});
