import fs from 'node:fs';import path from 'node:path';
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);const files=walk('.').filter(f=>/\.(ts|js|mjs|sql|jsonc|html)$/.test(f)&&!f.includes('apps/web/dist')&&!f.includes('node_modules')&&!f.endsWith('scripts/security-check.mjs')&&!f.endsWith('tests/security/visibility.test.ts')&&!f.endsWith('scripts/lint.mjs'));
const text=files.map(f=>`\n/* ${f} */\n${fs.readFileSync(f,'utf8')}`).join('');const errors=[];
for(const forbidden of ['match_seed TEXT','role_map TEXT','unrevealed_votes','/ws/rooms/'])if(text.includes(forbidden))errors.push(`Forbidden architecture marker: ${forbidden}`);
const browser=walk('apps/web').filter(f=>/\.(ts|js|html)$/.test(f)).map(f=>fs.readFileSync(f,'utf8')).join('\n');for(const secret of ['durableObjectId','durable_object_id','PIN_PEPPER','ROOM_CODE_LOOKUP_SECRET','INTERNAL_ROUTING_SECRET'])if(browser.includes(secret))errors.push(`Browser source contains ${secret}`);
const worker=fs.readFileSync('apps/worker/src/index.ts','utf8');if(!worker.includes('.newUniqueId()')||!worker.includes('.idFromString('))errors.push('Random DO identity path missing');if(!worker.includes('hmacSha256(code,env.ROOM_CODE_LOOKUP_SECRET)'))errors.push('HMAC room-code lookup missing');
const durable=fs.readFileSync('apps/worker/src/durable/MafiYaarRoom.ts','utf8');if(durable.indexOf('this.persist(next')>durable.indexOf('this.broadcast(room)')&&durable.indexOf('this.broadcast(room)')>=0)errors.push('Potential broadcast-before-persist ordering');if(!durable.includes('transactionSync'))errors.push('Atomic snapshot/journal transaction missing');
for(const f of files){const value=fs.readFileSync(f,'utf8');if(/console\.(log|error)\([^\n]*(PIN_PEPPER|SESSION_HASH_SECRET|ROOM_CODE_LOOKUP_SECRET|INVITATION_HASH_SECRET|INTERNAL_ROUTING_SECRET)/.test(value))errors.push(`${f}: secret logging risk`);}
console.log(JSON.stringify({ok:errors.length===0,filesScanned:files.length,errors},null,2));if(errors.length)process.exit(1);
