import {describe,it,expect} from 'vitest';
import {env} from 'cloudflare:workers';
import {D1ArchiveWriter} from '../../apps/worker/src/repositories/archive.js';
import {createMatch} from '../../packages/engine/index.js';
import {validateSettings} from '../../packages/validation/index.js';

describe('completed-match D1 archival',()=>{
  it('is idempotent for history and player statistics',async()=>{const now=Date.now(),members=Array.from({length:5},(_,i)=>({accountId:`archive-a${i}`,playerId:`archive-p${i}`,displayName:`Archive ${i}`,avatar:'moon',ready:true,connected:true}));for(const m of members){await env.DB.batch([env.DB.prepare('INSERT INTO accounts(id,username,pin_hash,pin_salt,pin_hash_version,pin_hash_parameters,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(m.accountId,`archive_${m.accountId}`,'h','s','v','{}',now,now),env.DB.prepare('INSERT INTO profiles(account_id,display_name,avatar,locale,updated_at) VALUES(?,?,?,?,?)').bind(m.accountId,m.displayName,'moon','ur-Roman',now),env.DB.prepare('INSERT INTO player_statistics(account_id,updated_at) VALUES(?,?)').bind(m.accountId,now)]);}const settings=validateSettings({playerLimit:5,mafiaCount:1,preset:'test'},true),match=createMatch({id:`archive-match-${crypto.randomUUID()}`,roomId:'ARCDE',members,settings,entropyId:'private',random:()=>0,now});match.winner='civilian';match.completedAt=now+1000;match.phase='summary';const room:any={id:'ARCDE',code:'ARCDE',inviteToken:'',creatorAccountId:members[0]!.accountId,status:'complete',settings,members,match,createdAt:now,expiresAt:now+10000,version:2};const writer=new D1ArchiveWriter(env);expect(await writer.archive(room,'archive-hmac')).toBe('created');expect(await writer.archive(room,'archive-hmac')).toBe('exists');const matches=await env.DB.prepare('SELECT count(*) c FROM completed_matches WHERE match_id=?').bind(match.id).first<any>();expect(matches.c).toBe(1);for(const m of members){const stats=await env.DB.prepare('SELECT matches_played FROM player_statistics WHERE account_id=?').bind(m.accountId).first<any>();expect(stats.matches_played).toBe(1);}});
});
